import type {
  PageTemplatePreset,
  SectionPreset,
  SectionPresetId,
} from './schema';

const innerFrame = {
  showLeftNav: true,
  showBackLink: true,
  backHref: '/',
  backLabel: 'HOME',
  topSpacingPreset: 'inner' as const,
  wideTopAdjustment: 'innerWide' as const,
};

export const pageTemplates: PageTemplatePreset[] = [
  {
    id: 'home-profile',
    label: 'Home profile',
    description: 'Avatar, thin divider, and short profile copy.',
    defaultFrame: {
      showLeftNav: true,
      showBackLink: false,
      backHref: '/',
      backLabel: 'HOME',
      topSpacingPreset: 'home',
      wideTopAdjustment: 'homeWide',
    },
  },
  {
    id: 'gallery-page',
    label: 'Single gallery page',
    description: 'One gallery section using a locked Cargo-style preset.',
    defaultFrame: innerFrame,
  },
  {
    id: 'segmented-gallery-page',
    label: 'Segmented gallery page',
    description: 'Multiple gallery sections with preserved inter-section gaps.',
    defaultFrame: innerFrame,
  },
  {
    id: 'gif-page',
    label: 'GIF hero and grid',
    description: 'Standalone hero GIF followed by a captionless dense GIF grid.',
    defaultFrame: {
      ...innerFrame,
      topSpacingPreset: 'tight',
    },
  },
  {
    id: 'photo-index',
    label: 'Photo album index',
    description: 'Photo entries that open dedicated album pages.',
    defaultFrame: {
      ...innerFrame,
      topSpacingPreset: 'photo',
    },
  },
  {
    id: 'photo-detail',
    label: 'Photo album detail',
    description: 'Image-only album column layout.',
    defaultFrame: {
      ...innerFrame,
      topSpacingPreset: 'photo',
    },
  },
  {
    id: 'rich-text',
    label: 'Rich text',
    description: 'Poem/prose body where WYSIWYG editing is appropriate.',
    defaultFrame: innerFrame,
  },
  {
    id: 'links',
    label: 'Links',
    description: 'Simple text or icon links.',
    defaultFrame: innerFrame,
  },
  {
    id: 'contact-drawer',
    label: 'Contact drawer',
    description: 'Right-side message drawer that preserves the original offset.',
    defaultFrame: {
      showLeftNav: true,
      showBackLink: false,
      backHref: '/',
      backLabel: 'HOME',
      topSpacingPreset: 'contact',
      wideTopAdjustment: 'innerWide',
      contactDrawer: true,
    },
  },
];

export const sectionPresets: SectionPreset[] = [
  {
    id: 'home-profile',
    label: 'Home avatar + bio',
    type: 'profile',
    defaults: {
      columns: 1,
      spacing: 'roomy',
      imageFit: 'cover-square',
      captionMode: 'none',
      clickMode: 'none',
      sectionGap: 'none',
      widthMode: 'content',
    },
    simpleControls: ['items'],
    advancedControls: ['widthMode', 'customWidthPercent'],
    requiredItemFields: ['id', 'src', 'width', 'height'],
    optionalItemFields: ['title', 'bodyHtml', 'href'],
  },
  {
    id: 'gallery-roomy-3',
    label: 'Roomy 3-column gallery',
    type: 'gallery',
    defaults: {
      columns: 3,
      spacing: 'roomy',
      imageFit: 'cover-square',
      captionMode: 'html',
      clickMode: 'lightbox',
      sectionGap: 'normal',
      widthMode: 'content',
      showCaptions: true,
    },
    simpleControls: ['items', 'captionMode'],
    advancedControls: ['columns', 'spacing', 'imageFit', 'sectionGap'],
    requiredItemFields: ['id', 'title', 'src', 'width', 'height'],
    optionalItemFields: ['year', 'desc', 'captionHtml', 'href', 'links'],
  },
  {
    id: 'gallery-dense-3',
    label: 'Dense natural 3-column gallery',
    type: 'gallery',
    defaults: {
      columns: 3,
      spacing: 'dense',
      imageFit: 'natural',
      captionMode: 'html',
      clickMode: 'lightbox',
      sectionGap: 'large',
      widthMode: 'content',
      showCaptions: true,
    },
    simpleControls: ['items', 'captionMode'],
    advancedControls: ['spacing', 'imageFit', 'sectionGap'],
    requiredItemFields: ['id', 'title', 'src', 'width', 'height'],
    optionalItemFields: ['year', 'captionHtml', 'href', 'links'],
  },
  {
    id: 'gallery-flush-3',
    label: 'Flush natural 3-column gallery',
    type: 'gallery',
    defaults: {
      columns: 3,
      spacing: 'flush',
      imageFit: 'natural',
      captionMode: 'html',
      clickMode: 'lightbox',
      sectionGap: 'large',
      widthMode: 'content',
      showCaptions: true,
    },
    simpleControls: ['items', 'captionMode'],
    advancedControls: ['spacing', 'imageFit', 'sectionGap'],
    requiredItemFields: ['id', 'title', 'src', 'width', 'height'],
    optionalItemFields: ['year', 'captionHtml', 'href', 'links'],
  },
  {
    id: 'gallery-dense-2',
    label: 'Dense natural 2-column gallery',
    type: 'gallery',
    defaults: {
      columns: 2,
      spacing: 'dense',
      imageFit: 'natural',
      captionMode: 'html',
      clickMode: 'lightbox',
      sectionGap: 'none',
      widthMode: 'content',
      showCaptions: true,
    },
    simpleControls: ['items', 'captionMode'],
    advancedControls: ['columns', 'spacing', 'imageFit'],
    requiredItemFields: ['id', 'title', 'src', 'width', 'height'],
    optionalItemFields: ['captionHtml', 'year', 'href', 'links'],
  },
  {
    id: 'gif-hero',
    label: 'GIF hero',
    type: 'gif-hero',
    defaults: {
      columns: 1,
      spacing: 'roomy',
      imageFit: 'natural',
      captionMode: 'none',
      clickMode: 'none',
      sectionGap: 'normal',
      widthMode: 'content',
      showCaptions: false,
    },
    simpleControls: ['items'],
    advancedControls: ['widthMode'],
    requiredItemFields: ['id', 'src', 'width', 'height'],
    optionalItemFields: ['title', 'href'],
  },
  {
    id: 'photo-index-columns',
    label: 'Photo index columns',
    type: 'photo-index',
    defaults: {
      columns: 3,
      spacing: 'roomy',
      imageFit: 'natural',
      captionMode: 'title-year',
      clickMode: 'internal-page',
      sectionGap: 'none',
      widthMode: 'content',
      showCaptions: true,
    },
    simpleControls: ['items'],
    advancedControls: ['columns', 'spacing', 'imageFit'],
    requiredItemFields: ['id', 'title', 'src', 'href', 'width', 'height'],
    optionalItemFields: ['year', 'targetPageId', 'originalUrl', 'displayUrl'],
  },
  {
    id: 'photo-detail-columns',
    label: 'Photo detail columns',
    type: 'photo-detail',
    defaults: {
      columns: 3,
      spacing: 'roomy',
      imageFit: 'natural',
      captionMode: 'none',
      clickMode: 'lightbox',
      sectionGap: 'none',
      widthMode: 'content',
      showCaptions: false,
    },
    simpleControls: ['items'],
    advancedControls: ['columns', 'spacing', 'imageFit'],
    requiredItemFields: ['id', 'src', 'width', 'height'],
    optionalItemFields: ['title', 'year', 'originalUrl', 'displayUrl'],
  },
  {
    id: 'rich-text-poem',
    label: 'Poem rich text',
    type: 'rich-text',
    defaults: {
      columns: 1,
      spacing: 'roomy',
      imageFit: 'contain',
      captionMode: 'none',
      clickMode: 'none',
      sectionGap: 'none',
      widthMode: 'content',
    },
    simpleControls: ['items'],
    advancedControls: ['widthMode', 'customWidthPercent'],
    requiredItemFields: ['id', 'bodyHtml'],
    optionalItemFields: ['title'],
  },
  {
    id: 'sns-icons',
    label: 'Social links',
    type: 'links',
    defaults: {
      columns: 1,
      spacing: 'roomy',
      captionMode: 'none',
      clickMode: 'external-link',
      sectionGap: 'none',
      widthMode: 'content',
    },
    simpleControls: ['items'],
    advancedControls: ['spacing'],
    requiredItemFields: ['id', 'title', 'href'],
    optionalItemFields: ['src'],
  },
  {
    id: 'single-link',
    label: 'Single link list',
    type: 'links',
    defaults: {
      columns: 1,
      spacing: 'roomy',
      captionMode: 'none',
      clickMode: 'external-link',
      sectionGap: 'none',
      widthMode: 'content',
    },
    simpleControls: ['items'],
    advancedControls: ['spacing'],
    requiredItemFields: ['id', 'title', 'href'],
    optionalItemFields: ['desc'],
  },
  {
    id: 'contact-message',
    label: 'Contact message drawer',
    type: 'contact',
    defaults: {
      columns: 1,
      spacing: 'roomy',
      captionMode: 'none',
      clickMode: 'none',
      sectionGap: 'none',
      widthMode: 'custom',
      customWidthPercent: 58,
    },
    simpleControls: ['items'],
    advancedControls: ['customWidthPercent'],
    requiredItemFields: ['id', 'bodyHtml'],
    optionalItemFields: ['title'],
  },
];

export const presets = {
  pageTemplates,
  sectionPresets,
};

export const sectionPresetMap = new Map<SectionPresetId, SectionPreset>(
  sectionPresets.map((preset) => [preset.id, preset]),
);
